// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub_msg.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HubMsg struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Msg                  []byte   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HubMsg) Reset()         { *m = HubMsg{} }
func (m *HubMsg) String() string { return proto.CompactTextString(m) }
func (*HubMsg) ProtoMessage()    {}
func (*HubMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_957d59ecbccfb61c, []int{0}
}

func (m *HubMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HubMsg.Unmarshal(m, b)
}
func (m *HubMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HubMsg.Marshal(b, m, deterministic)
}
func (m *HubMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HubMsg.Merge(m, src)
}
func (m *HubMsg) XXX_Size() int {
	return xxx_messageInfo_HubMsg.Size(m)
}
func (m *HubMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HubMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HubMsg proto.InternalMessageInfo

func (m *HubMsg) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HubMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*HubMsg)(nil), "pb.HubMsg")
}

func init() { proto.RegisterFile("hub_msg.proto", fileDescriptor_957d59ecbccfb61c) }

var fileDescriptor_957d59ecbccfb61c = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x28, 0x4d, 0x8a,
	0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xd2, 0xe3,
	0x62, 0xf3, 0x28, 0x4d, 0xf2, 0x2d, 0x4e, 0x17, 0x12, 0xe2, 0x62, 0x09, 0xa9, 0x2c, 0x48, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98, 0x7d, 0x8b, 0xd3, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x40, 0xcc, 0x24, 0x36, 0xb0, 0x56, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfc, 0x13, 0xb7, 0x1b, 0x4b, 0x00, 0x00, 0x00,
}
