// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageData struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	PeerId    string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*Response_Error
	//	*Response_Fstree
	Result               isResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *Response) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type isResponse_Result interface {
	isResponse_Result()
}

type Response_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Response_Fstree struct {
	Fstree *FSTree `protobuf:"bytes,4,opt,name=fstree,proto3,oneof"`
}

func (*Response_Error) isResponse_Result() {}

func (*Response_Fstree) isResponse_Result() {}

func (m *Response) GetResult() isResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Response) GetError() string {
	if x, ok := m.GetResult().(*Response_Error); ok {
		return x.Error
	}
	return ""
}

func (m *Response) GetFstree() *FSTree {
	if x, ok := m.GetResult().(*Response_Fstree); ok {
		return x.Fstree
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Error)(nil),
		(*Response_Fstree)(nil),
	}
}

type Request struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	RequestId            string   `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *Request) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageData)(nil), "pb.MessageData")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*Request)(nil), "pb.Request")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x45, 0x9b, 0xaa, 0x99, 0xce, 0xeb, 0x42, 0xc8, 0x42, 0x83, 0x20, 0x94, 0x41, 0xb0, 0xab,
	0x59, 0xd4, 0x3f, 0x10, 0x91, 0x76, 0xe1, 0x26, 0xba, 0x71, 0x55, 0x66, 0xc8, 0xad, 0x16, 0x3a,
	0x26, 0xbe, 0x64, 0x7e, 0xc2, 0xaf, 0x96, 0x4c, 0xe2, 0x17, 0xb8, 0x3c, 0xf7, 0x84, 0x70, 0x78,
	0x54, 0xfb, 0x8d, 0x6f, 0x3d, 0xbb, 0xe8, 0xd4, 0xdc, 0xf7, 0x37, 0x97, 0x87, 0xe3, 0x09, 0xfb,
	0xc8, 0x40, 0x1e, 0x9b, 0x7b, 0x5a, 0xbe, 0x20, 0x84, 0xee, 0x03, 0x4f, 0x5d, 0xec, 0x94, 0xa6,
	0x6a, 0xc8, 0xa8, 0xc5, 0x4a, 0xac, 0x6b, 0xf3, 0x87, 0xcd, 0x8f, 0xa0, 0x85, 0x41, 0xf0, 0xee,
	0x2b, 0x40, 0x5d, 0x53, 0xe5, 0x01, 0xde, 0x1f, 0x6d, 0x79, 0x26, 0x13, 0xee, 0xac, 0xba, 0x25,
	0x62, 0x7c, 0x8f, 0x08, 0x31, 0xb9, 0xf9, 0xe4, 0xea, 0xb2, 0xec, 0xac, 0xba, 0xa2, 0x0b, 0x30,
	0x3b, 0xd6, 0x67, 0xc9, 0x6c, 0x67, 0x26, 0xa3, 0xba, 0x23, 0x79, 0x08, 0xa9, 0x4a, 0x9f, 0xaf,
	0xc4, 0x7a, 0xb9, 0xa1, 0xd6, 0xf7, 0xed, 0xf3, 0xeb, 0x1b, 0x03, 0xdb, 0x99, 0x29, 0xee, 0x71,
	0x41, 0x92, 0x11, 0xc6, 0x53, 0x6c, 0xde, 0xa9, 0x32, 0xf9, 0xd3, 0x7f, 0xa4, 0xc8, 0x01, 0xf1,
	0xd3, 0xd9, 0xdc, 0x62, 0x0a, 0xf5, 0x72, 0xba, 0xcb, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x39, 0x92, 0xd1, 0x4c, 0x39, 0x01, 0x00, 0x00,
}
