// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portal_msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payload struct {
	// Types that are valid to be assigned to Msg:
	//	*Payload_Login
	//	*Payload_Register
	Msg                  isPayload_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6df4aabe22a97ec1, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

type isPayload_Msg interface {
	isPayload_Msg()
}

type Payload_Login struct {
	Login *LoginPayload `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type Payload_Register struct {
	Register *RegisterPayload `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

func (*Payload_Login) isPayload_Msg() {}

func (*Payload_Register) isPayload_Msg() {}

func (m *Payload) GetMsg() isPayload_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Payload) GetLogin() *LoginPayload {
	if x, ok := m.GetMsg().(*Payload_Login); ok {
		return x.Login
	}
	return nil
}

func (m *Payload) GetRegister() *RegisterPayload {
	if x, ok := m.GetMsg().(*Payload_Register); ok {
		return x.Register
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Payload) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Payload_Login)(nil),
		(*Payload_Register)(nil),
	}
}

type LoginPayload struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginPayload) Reset()         { *m = LoginPayload{} }
func (m *LoginPayload) String() string { return proto.CompactTextString(m) }
func (*LoginPayload) ProtoMessage()    {}
func (*LoginPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6df4aabe22a97ec1, []int{1}
}

func (m *LoginPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginPayload.Unmarshal(m, b)
}
func (m *LoginPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginPayload.Marshal(b, m, deterministic)
}
func (m *LoginPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginPayload.Merge(m, src)
}
func (m *LoginPayload) XXX_Size() int {
	return xxx_messageInfo_LoginPayload.Size(m)
}
func (m *LoginPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginPayload.DiscardUnknown(m)
}

var xxx_messageInfo_LoginPayload proto.InternalMessageInfo

func (m *LoginPayload) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterPayload struct {
	// to add more user details here
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterPayload) Reset()         { *m = RegisterPayload{} }
func (m *RegisterPayload) String() string { return proto.CompactTextString(m) }
func (*RegisterPayload) ProtoMessage()    {}
func (*RegisterPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6df4aabe22a97ec1, []int{2}
}

func (m *RegisterPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterPayload.Unmarshal(m, b)
}
func (m *RegisterPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterPayload.Marshal(b, m, deterministic)
}
func (m *RegisterPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterPayload.Merge(m, src)
}
func (m *RegisterPayload) XXX_Size() int {
	return xxx_messageInfo_RegisterPayload.Size(m)
}
func (m *RegisterPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterPayload.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterPayload proto.InternalMessageInfo

func (m *RegisterPayload) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PortalResp struct {
	// Types that are valid to be assigned to Resp:
	//	*PortalResp_Token
	//	*PortalResp_User
	Resp                 isPortalResp_Resp `protobuf_oneof:"resp"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PortalResp) Reset()         { *m = PortalResp{} }
func (m *PortalResp) String() string { return proto.CompactTextString(m) }
func (*PortalResp) ProtoMessage()    {}
func (*PortalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6df4aabe22a97ec1, []int{3}
}

func (m *PortalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortalResp.Unmarshal(m, b)
}
func (m *PortalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortalResp.Marshal(b, m, deterministic)
}
func (m *PortalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortalResp.Merge(m, src)
}
func (m *PortalResp) XXX_Size() int {
	return xxx_messageInfo_PortalResp.Size(m)
}
func (m *PortalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PortalResp.DiscardUnknown(m)
}

var xxx_messageInfo_PortalResp proto.InternalMessageInfo

type isPortalResp_Resp interface {
	isPortalResp_Resp()
}

type PortalResp_Token struct {
	Token string `protobuf:"bytes,2,opt,name=token,proto3,oneof"`
}

type PortalResp_User struct {
	User *User `protobuf:"bytes,3,opt,name=user,proto3,oneof"`
}

func (*PortalResp_Token) isPortalResp_Resp() {}

func (*PortalResp_User) isPortalResp_Resp() {}

func (m *PortalResp) GetResp() isPortalResp_Resp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *PortalResp) GetToken() string {
	if x, ok := m.GetResp().(*PortalResp_Token); ok {
		return x.Token
	}
	return ""
}

func (m *PortalResp) GetUser() *User {
	if x, ok := m.GetResp().(*PortalResp_User); ok {
		return x.User
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PortalResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PortalResp_Token)(nil),
		(*PortalResp_User)(nil),
	}
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_6df4aabe22a97ec1, []int{4}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type User struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxDevices           int64      `protobuf:"varint,2,opt,name=max_devices,json=maxDevices,proto3" json:"max_devices,omitempty"`
	Devices              []*Devices `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6df4aabe22a97ec1, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetMaxDevices() int64 {
	if m != nil {
		return m.MaxDevices
	}
	return 0
}

func (m *User) GetDevices() []*Devices {
	if m != nil {
		return m.Devices
	}
	return nil
}

type Devices struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devices) Reset()         { *m = Devices{} }
func (m *Devices) String() string { return proto.CompactTextString(m) }
func (*Devices) ProtoMessage()    {}
func (*Devices) Descriptor() ([]byte, []int) {
	return fileDescriptor_6df4aabe22a97ec1, []int{6}
}

func (m *Devices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices.Unmarshal(m, b)
}
func (m *Devices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices.Marshal(b, m, deterministic)
}
func (m *Devices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices.Merge(m, src)
}
func (m *Devices) XXX_Size() int {
	return xxx_messageInfo_Devices.Size(m)
}
func (m *Devices) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices.DiscardUnknown(m)
}

var xxx_messageInfo_Devices proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Payload)(nil), "pb.Payload")
	proto.RegisterType((*LoginPayload)(nil), "pb.LoginPayload")
	proto.RegisterType((*RegisterPayload)(nil), "pb.RegisterPayload")
	proto.RegisterType((*PortalResp)(nil), "pb.PortalResp")
	proto.RegisterType((*Token)(nil), "pb.Token")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Devices)(nil), "pb.Devices")
}

func init() { proto.RegisterFile("portal_msg.proto", fileDescriptor_6df4aabe22a97ec1) }

var fileDescriptor_6df4aabe22a97ec1 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x5d, 0x4b, 0xf3, 0x30,
	0x14, 0xde, 0xd6, 0x76, 0x6b, 0x4f, 0x5f, 0x78, 0x47, 0x14, 0x29, 0x82, 0x3a, 0x02, 0x42, 0xaf,
	0x0a, 0xce, 0x7f, 0x30, 0x44, 0x26, 0xec, 0x62, 0x04, 0xbd, 0x1e, 0xa9, 0x0d, 0xa5, 0xd8, 0x34,
	0x21, 0xa9, 0x3a, 0xff, 0xbd, 0xe4, 0xf4, 0xc3, 0xe1, 0xa5, 0x77, 0x7d, 0x3e, 0xce, 0x73, 0x9e,
	0xd3, 0xc0, 0x52, 0x2b, 0xd3, 0xf2, 0xfa, 0x20, 0x6d, 0x99, 0x69, 0xa3, 0x5a, 0x45, 0x66, 0x3a,
	0xa7, 0x12, 0x16, 0x7b, 0xfe, 0x55, 0x2b, 0x5e, 0x90, 0x14, 0x82, 0x5a, 0x95, 0x55, 0x93, 0x4c,
	0x57, 0xd3, 0x34, 0x5e, 0x2f, 0x33, 0x9d, 0x67, 0x3b, 0x47, 0xf4, 0x86, 0xed, 0x84, 0x75, 0x06,
	0x72, 0x07, 0xa1, 0x11, 0x65, 0x65, 0x5b, 0x61, 0x92, 0x19, 0x9a, 0xcf, 0x9c, 0x99, 0xf5, 0xdc,
	0x8f, 0x7f, 0xb4, 0x6d, 0x02, 0xf0, 0xa4, 0x2d, 0xe9, 0x23, 0xfc, 0x3b, 0x8d, 0x24, 0x97, 0x10,
	0xbe, 0x5b, 0x61, 0x1a, 0x2e, 0x05, 0xae, 0x8d, 0xd8, 0x88, 0x9d, 0xa6, 0xb9, 0xb5, 0x9f, 0xca,
	0x14, 0xb8, 0x25, 0x62, 0x23, 0xa6, 0x4f, 0xf0, 0xff, 0xd7, 0xb6, 0x3f, 0x47, 0xed, 0x00, 0xf6,
	0xf8, 0x67, 0x98, 0xb0, 0x9a, 0x5c, 0x40, 0xd0, 0xaa, 0x37, 0xd1, 0x74, 0x36, 0x77, 0x32, 0x42,
	0x72, 0x0d, 0xbe, 0x4b, 0x4b, 0x3c, 0x3c, 0x37, 0x74, 0xe7, 0xbe, 0x58, 0x61, 0xb6, 0x13, 0x86,
	0xfc, 0x66, 0x0e, 0xbe, 0x11, 0x56, 0xd3, 0x2b, 0x08, 0x9e, 0x71, 0xe0, 0x7c, 0x08, 0xea, 0xba,
	0x74, 0x80, 0xe6, 0xe0, 0xbb, 0x31, 0x42, 0xc0, 0x3f, 0x29, 0x8a, 0xdf, 0xe4, 0x06, 0x62, 0xc9,
	0x8f, 0x87, 0x42, 0x7c, 0x54, 0xaf, 0xc2, 0x62, 0x01, 0x8f, 0x81, 0xe4, 0xc7, 0x87, 0x8e, 0x21,
	0xb7, 0xb0, 0x18, 0x44, 0x6f, 0xe5, 0xa5, 0xf1, 0x3a, 0x76, 0x35, 0x7a, 0x95, 0x0d, 0x1a, 0x8d,
	0x60, 0xd1, 0x73, 0xf9, 0x1c, 0x1f, 0xfa, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x70, 0x9e,
	0xa7, 0xfc, 0x01, 0x00, 0x00,
}
